auth_enabled: false # вкл/выкл аутентификацию в Loki

server:
  http_listen_port: 3100 # стандартный порт Loki

common:
  path_prefix: /loki # куда Loki пишет данные
  storage:
    filesystem:
      chunks_directory: /loki/chunks # чанки логов
      rules_directory: /loki/rules # правила (если будут)
  replication_factor: 1 # одиночный инстанс
  ring:
    kvstore:
      store: inmemory # локальное хранилище состояния

schema_config:
  configs:
    - from: 2023-01-01 # с какой даты схема
      store: boltdb-shipper # стандарт для локального старта
      object_store: filesystem # хранение на диске
      schema: v11 # версия схемы
      index:
        prefix: index_
        period: 24h # один индекс в день
